- MediaManager/Plugin.MediaManager.Android/MediaManagerImplementation.cs
- MediaManager/Plugin.MediaManager.Android/MediaPlayerService.cs
- Sample/MediaSample.Core/MediaPlayerManager.cs
- Sample/MediaSample.Droid/MainActivity.cs
> Fixes for Android: Files can be played again from URI

- MediaManager/Plugin.MediaManager.Abstractions/IMediaFile.cs
- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaFile.cs
- MediaManager/Plugin.MediaManager.iOS/MediaExtractorImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/MediaManagerImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/Plugin.MediaManager.iOS.csproj
- MediaManager/Plugin.MediaManager.iOS/VideoPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/VideoSurface.cs
It also adds a MediaExtractor for iOS
> This PR adds video playback support for iOS

- MediaManager/Plugin.MediaManager.Forms/Plugin.MediaManager.Forms.iOS/Plugin.MediaManager.Forms.iOS.csproj
- MediaManager/Plugin.MediaManager.Forms/Plugin.MediaManager.Forms.iOS/VideoViewRenderer.cs
- MediaManager/Plugin.MediaManager.iOS/VideoPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/VideoSurface.cs
- Samples/Forms/iOS/MediaForms.iOS.csproj
- Samples/Simple/MediaSample.iOS/Info.plist
- Samples/Simple/MediaSample.iOS/Main.storyboard
- Samples/Simple/MediaSample.iOS/MediaSample.iOS.csproj
- Samples/Simple/MediaSample.iOS/ViewController.cs
- Samples/Simple/MediaSample.iOS/ViewController.designer.cs
This also adds a simple sample for iOS
> Fix Xamarin Forms iOS sample

- MediaManager/Plugin.MediaManager.Android/Audio/AudioPlayerBroadcastReceiver.cs
- MediaManager/Plugin.MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
Added null reference checks to MediaServiceBase.HandleIntent().
Changed AudioPlayerBroadcastReceiver.OnReceive() so that if headphones are unplugged or Buetooth turned off, it pauses instead of stopping.
> Added null reference checks and improved noisy audio handling

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
This PR fixes a null reference when trying to instantiate the AudioPlayerImplementation for iOS
> Fix null reference in ctor

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
This adds custom header functionality to iOS.
There is one thing you should not with this pull request, and that is that it actually uses private apple apis. The key `"AVURLAssetHTTPHeaderFieldsKey"` is a private key and in theory, apple could reject your app for using this key. What I've read from others however is that it does not get rejected. None of the native compile-time [inspection tools](http://stackoverflow.com/questions/2842357/how-does-apple-know-you-are-using-private-api) apple uses should work on this code because it all happens at run-time. The only way Apple could find this is by checking it at run-time, where it is only used if you're actually using headers, or by inspecting the dll which I highly doubt Apple will do.
I will post back here once we've released our app that …
> Custom headers iOS

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/MediaExtractorImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/MediaFileUrlHelper.cs
- MediaManager/Plugin.MediaManager.iOS/Plugin.MediaManager.iOS.csproj
- Samples/Simple/MediaSample.iOS/MediaSample.iOS.csproj
- Samples/Simple/MediaSample.iOS/ViewController.cs
Added support for local files on iOS.
> Local files support iOS

- MediaManager/Plugin.MediaManager.Android/MediaManagerImplementation.cs
Fixed Android media notification play previous behaviour to be consistent with iOS behaviour.
> Fixed Android media notification play previous behaviour.

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaManagerBase.cs
Update notifications once the file really starts playing to solve problems with various race conditions. This would cause the iOS Media Notification to not display any duration or progress. This occurs with specific types of files, so I changed it to call UpdateNotification once the media really started playing.
> Fixed MediaNotifications bug iOS

- MediaManager/Plugin.MediaManager.Android/Audio/AudioPlayerBase.cs
- MediaManager/Plugin.MediaManager.ExoPlayer/Plugin.MediaManager.ExoPlayer.csproj
- MediaManager/Plugin.MediaManager.ExoPlayer/packages.config
- Samples/Simple/MediaSample.Droid/MainActivity.cs
- Recoverd basic playback functionality on Android
- Downgraded ExoPlayer to make it compile
- Added boolean in the sample for easy switching between ExoPlayer and native player.
> Resume Fix Android

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
This is a commit that belongs to another pull request but since that is already merged, I created a new one.
- Removed unnecesary version check to make it compatible with MacOS.
> Fixed issue with buffering on iOS 10 and greater. 

- MediaManager/Plugin.MediaManager.Android/Audio/AudioPlayerBase.cs
- MediaManager/Plugin.MediaManager.Android/MediaPlayerService/MediaPlayerService.cs
- MediaManager/Plugin.MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
- MediaManager/Plugin.MediaManager.ExoPlayer/ExoPlayerAudioService.cs
> Fixed issue with resuming in the stock Android implementation.

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaQueue.cs
- MediaManager/Plugin.MediaManager.Tests/Unit/MediaQueueTests.cs
Added check to ensure only one collection changed event gets fired on AddRange.
> AddRange CollectionChanged fix

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
This memory leak happened because the `PeriodicTimeObserver` was not properly removed. It caused the CPU usage to grow after playing a couple of track because the time observers were still running the the background even though the AVPlayer had been disposed.
> Fixed iOS memory leak

- MediaManager/Plugin.MediaManager.Android/Audio/AudioPlayerBroadcastReceiver.cs
- MediaManager/Plugin.MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
Fixes issue regarding pulling headphones out the the track continuing… to play.
> Audio Headphones Unplugged Fix 

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
Fixed problem where status wasn’t updated when the system changed the rate because of an interruption, like a phone call, headphones plugged out etc.
> System interruption status fix

- MediaManager.ExoPlayer/ExoPlayerAudioService.cs
> Fixed OverflowException in ExoPlayerAudioService.OnBuffering

- MediaManager.UWP/AudioPlayerImplementation.cs
- Samples/Simple/MediaSample.UWP/MainPage.xaml.cs
> Fix Resume issue on UWP

- MediaManager.UWP/AudioPlayerImplementation.cs
- Samples/Simple/MediaSample.UWP/MainPage.xaml
- Samples/Simple/MediaSample.UWP/MainPage.xaml.cs
Hi @martijn00 
This fixes the issue #228 
Please review my changes and let me know if there're any issues with those.
Regards,
Jay
> Uwp seekto fix

- MediaManager.UWP/Plugin.MediaManager.UWP.csproj
Added poject.json file to MediaManager.UWP.csproj, which should fix the compilation problem (at least locally after a couple of rebuilds the entire solution complies)
> Get solution to compile (hopefully)

- MediaManager.Abstractions/IVideoPlayer.cs
- MediaManager.Abstractions/IVideoSurface.cs
- MediaManager.Abstractions/Implementations/MediaManagerBase.cs
- MediaManager.Android/Audio/AudioPlayerBase.cs
- MediaManager.Android/Video/VideoPlayerImplementation.cs
- MediaManager.Android/Video/VideoSurface.cs
- MediaManager.Forms/MediaManager.Forms.Android/VideoViewRenderer.cs
- MediaManager.Forms/MediaManager.Forms/VideoView.cs
- MediaManager.MacOS/VideoSurface.cs
- MediaManager.UWP/MediaManagerImplementation.cs
- MediaManager.UWP/VideoPlayerImplementation.cs
- MediaManager.UWP/VideoSurface.cs
- MediaManager.iOS/VideoPlayerImplementation.cs
- MediaManager.iOS/VideoSurface.cs
- MediaManager.tvOS/VideoSurface.cs
- Samples/Forms/MediaForms/App.xaml.cs
- Samples/Forms/MediaForms/HomePage.xaml
- Samples/Forms/MediaForms/HomePage.xaml.cs
- Samples/Forms/MediaForms/MediaForms.csproj
- Samples/Forms/MediaForms/MediaFormsPage.xaml
- Samples/Forms/MediaForms/MediaFormsPage.xaml.cs
Analysis of the 2 bugs:
https://github.com/martijn00/XamarinMediaManager/issues/238
https://github.com/martijn00/XamarinMediaManager/issues/239
> Fixed #238 and #239

- MediaManager.Forms/MediaManager.Forms.UWP/VideoViewRenderer.cs
- MediaManager.UWP/VideoPlayerImplementation.cs
These modifications should fix the #203 and #82 issues.
> Fix uwp video rendering

- MediaManager.Android/MediaManagerImplementation.cs
- MediaManager.Android/MediaSession/MediaNotificationManagerImplementation.cs
- MediaManager.Android/MediaSession/MediaSessionManager.cs
- Samples/Forms/MediaForms/HomePage.xaml
- Samples/Forms/MediaForms/HomePage.xaml.cs
Hi @martijn00 ,
I've created the pull request that will resolve an issue #265 
Could you please review it and let me know if there're issues there?
Kind Regards,
Jay Sim
> Add prev/next buttons when it's available

- MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
- MediaManager.Android/MediaSession/MediaNotificationManagerImplementation.cs
Here are a number of commits that fix some issues related to Notifications on Android.
***I am new to git PRs and didn't realize how it will stack multiple commits into a single PR but include the comments for each commit.  Hopefully this is how you prefer to get these PRs, if not please let me know and I will happily submit them to your preference.  Sorry for the Revert of a Revert, some issues with the git interface on my part.***
> Notification Related Fixes

- MediaManager.Abstractions/IMediaFile.cs
- MediaManager.Abstractions/Implementations/MediaManagerBase.cs
- Samples/Forms/MediaForms/HomePage.xaml.cs
Changes to support user entered metadata for Android notifications
> Changes to resolve metadata issue

- MediaManager.Abstractions/IPlaybackController.cs
- MediaManager.UWP/AudioPlayerImplementation.cs
- MediaManager.UWP/MediaManagerImplementation.cs
- MediaManager.UWP/MediaNotificationManagerImplementation.cs
- MediaManager.UWP/VideoPlayerImplementation.cs
- MediaManager.iOS/AudioPlayerImplementation.cs
- MediaManager.iOS/MediaFileUrlHelper.cs
- MediaManager.iOS/MediaManagerAppleBase.cs
- MediaManager.iOS/MediaManagerImplementation.cs
- MediaManager.iOS/MediaNotificationManagerImplementation.cs
- MediaManager.iOS/MediaRemoteControl.cs
- MediaManager.iOS/VideoPlayerImplementation.cs
I was able to get all of the IOS Projects cleaned up.
UWP is kicking out 1300+ errors, System.Object not defined etc. I am unfamiliar with UWP and what may be missing (or may be .Net Standard bugs) causing the inability to compile.  I cleaned up what I could find in the errors list, so it should be close once the System dependencies or whatever is resolved.
> IOS Refactoring & Partial UWP Refactoring

- MediaManager.iOS/AudioPlayerImplementation.cs
- MediaManager.iOS/VideoPlayerImplementation.cs
- MediaManager.iOS/VolumeManagerImplementation.cs
Primarily fixed the Volume getter on iOS to get the correct volume as well as changed the VolumeManager to directly access the AVMediaPlayer on the Audio and Video Implementations.
Sorry for the double PR, I missed a rounding error the first go around.
> iOS Volume Fixes

- MediaManager.Abstractions/Implementations/MediaManagerBase.cs
- MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
- Samples/Forms/MediaForms/HomePage.xaml.cs
Resolve an issue that media queue always starts from 1 when playing a list of media files (#290)
Add buffering state before playing the file for android (resolving an issue #255)
> Resolving issue #255 and #290

- MediaManager.Android/MediaPlayerService/MediaPlayerService.cs
> Fix bug when playing same song

- MediaManager/MediaManagerBase.cs
- MediaManager/Playback/BufferingChangedEventArgs.cs
- MediaManager/Playback/IPlaybackManager.cs
- MediaManager/Playback/PositionChangedEventArgs.cs
- Samples/ElementPlayer.Core/ViewModels/PlayerViewModel.cs
Feature
We can't track a changed position in the player
We have an event handler (and in the sample app an event listener) which can update the data
No
See the android sample
> Added a position changed event listener

- MediaManager/MediaManagerBase.cs
Bug fix
It is impossible to step forward after a minute, it will move you backward
You can just keep on skipping backwards and forwards as you wish
No
> We now use the totalseconds instead of the seconds

- README.md
Docs update
Some info missing in the docs
Some more info in the docs
No
> Added some additional info to the readme.MD

- README.md
I'm confused with X being supported or unsupported
Trivial changes in README.md
Confusing
Not confusing
No
No
- [ ✓] All projects build
- [ ✓] Follows style guide lines 
- [ ✓] Relevant documentation was updated
- [ X] Rebased onto current develop
> Changed X to ✓ in the table of supported features.

- MediaManager/Platforms/Ios/Video/VideoView.cs
Bug fix
Application is not responding on disappearing on iOS (only Xamarin.Forms)
Application is now responding
no
1.Play a media item
2.Click on back button
3.Application is responding
#534
> Application is not responding on disappearing on iOS (only Xamarin.Forms)

- MediaManager/Media/MediaItem.cs
- MediaManager/Media/MediaLocation.cs
- MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
- MediaManager/Platforms/Apple/Media/AppleMediaExtractor.cs
- MediaManager/Platforms/Apple/Player/MediaItemExtensions.cs
- MediaManager/Platforms/Tizen/Media/MediaItemExtensions.cs
feature
playing media from file is not supported
playing from file is now supported by URL, FileInfo, and DirectoryInfo (to play all files in a directory)
no
> Play media from file on iOS

- MediaManager/Media/MediaExtractorBase.cs
- MediaManager/Platforms/Android/Media/MediaExtractor.cs
- MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
- MediaManager/Platforms/Apple/Media/AppleMediaExtractor.cs
- MediaManager/Platforms/Ios/Video/PlayerViewController.cs
- MediaManager/Platforms/Ios/Video/VideoView.cs
- MediaManager/Platforms/Uap/Media/MediaExtractor.cs
- MediaManager/Platforms/Uap/MediaManagerImplementation.cs
feature/fix
- local files are not loaded correctly
- local files are loaded on UWP and Android
- MediaExtractors is a bit cleaned (shared code is extracted to the base class)
no
> Play local file on UWP and Android adjustments and MediaExtractor Refactor

- MediaManager/IMediaManager.cs
- MediaManager/Media/IMediaExtractor.cs
- MediaManager/Media/MediaExtractorBase.cs
- MediaManager/Media/MediaLocation.cs
- MediaManager/MediaManagerBase.cs
- MediaManager/Platforms/Apple/Media/AppleMediaExtractor.cs
- MediaManager/Platforms/Apple/Player/MediaItemExtensions.cs
feature
Embedded resources media are not supported
Support to embedded resources media added
no
> Add support for embedded resources media

- MediaManager/Platforms/Uap/MediaManagerImplementation.cs
- Samples/ElementPlayer.Core/ViewModels/HomeViewModel.cs
Bug fix
example Forms.UWP project is not running
example Forms.UWP project is running
no
> Fix run Forms.UWP example project

- MediaManager/Platforms/Ios/Video/PlayerViewController.cs
- MediaManager/Platforms/Ios/Video/VideoView.cs
fix
ViewWillAppear of PlayerViewController is not called
ViewWillAppear of PlayerViewController is called
no
> Add PlayerViewController to parent ViewController of VideoView

- MediaManager/Platforms/Android/MediaManagerImplementation.cs
> Add wake lock permission

- Directory.build.props
- MediaManager/IMediaManager.cs
- MediaManager/Media/IMediaExtractor.cs
- MediaManager/Media/MediaExtractorBase.cs
- MediaManager/Media/MediaLocation.cs
- MediaManager/MediaManagerBase.cs
- MediaManager/Platforms/Android/Media/MediaExtractor.cs
- MediaManager/Platforms/Apple/Media/AppleMediaExtractor.cs
- MediaManager/Platforms/Tizen/Media/MediaExtractor.cs
- MediaManager/Platforms/Uap/Media/MediaExtractor.cs
- MediaManager/Platforms/Wpf/Media/MediaExtractor.cs
- README.md
feature
iOS and Android native resources are not supported
support for native resources added for iOS and Android
no
> Add support for native resources (iOS, Android)

- MediaManager/Media/IMediaExtractor.cs
- MediaManager/Media/MediaExtractorBase.cs
- MediaManager/Platforms/Android/Media/MediaExtractor.cs
- MediaManager/Platforms/Apple/Media/AppleMediaExtractor.cs
- MediaManager/Platforms/Tizen/Media/MediaExtractor.cs
- MediaManager/Platforms/Uap/Media/MediaExtractor.cs
- MediaManager/Platforms/Wpf/Media/MediaExtractor.cs
feature
MediaItemImage is improved
no
#574
> Placeholder image

- build.cake
> Try update CI

- MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs
#637 fixed exception with try catch so app does not crash anymore
Huawei  crashes on PrepareNotificationManager();
No more crash on Huawei on PrepareNotificationManager();
> #637 fixed exception with try catch so app does not crash anymore

- MediaManager/Platforms/Apple/Player/AppleMediaPlayer.cs
> Add nullcheck on current

- MediaManager/Platforms/Uap/Media/StorageFileProvider.cs
> Moves creation of bitmapImage in StorageFileProvider to ui thread

- README.md
docs
Building the source code: Windows 10 SDK added
I fall into bad compiling errors and don't know why... That was the reason 🦄
> Update README: Building the source code: Windows 10 SDK added

- MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs
- MediaManager/Platforms/Android/MediaSession/NotificationListener.cs
- MediaManager/Platforms/Android/Player/PlayerEventListener.cs
> Fixes to work with newer version of ExoPlayer.

- MediaManager/Platforms/Android/Queue/QueueDataAdapter.cs
Leftovers from #781 
It looks like traverse through multiple items correctly.
> Fix collection changes

- MediaManager/Platforms/Ios/Video/PlayerViewController.cs
Fixes the iOS full screen video issue
Test with playing a full screen video on an iPhone.
https://github.com/Baseflow/XamarinMediaManager/issues/629
> Fixes #629 and Tidied up the code from Jearom.

- MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs
Bug fix
App is killed for excessive CPU use when it is playing audio in the background and the foreground service is not running
No
See repro steps for issue #860
Addresses issue #860 
- [ x ] All projects build
- [ x ] Follows style guide lines 
- [ x ] Relevant documentation was updated
- [ x ] Rebased onto current develop
> Restart foreground service after pause

- MediaManager/MediaManager.csproj
- MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs
- MediaManager/Platforms/Android/Resources/values/string.xml
> Fix so that Android Notification spawns
