Baseflow/XamarinMediaManager

- MediaManager/Plugin.MediaManager.Android/MediaPlayerService.cs
1) Fixed NullReferenceException in MediaPlayerService.HandleIntent by adding null checks.
2) Fixed Java.Lang.RuntimeException: WifiLock under-locked in call to WifiLock.Release() in MediaPlayerService.ReleaseWifiLock(), by checking to make sure that the lock is actually held before the call.
3) Fixed IllegalStateException in call to MediaPlayer.Reset() in MediaPlayerService.Stop() by catching the exception.
> Fixed several unhandled exceptions that were causing crashes.

- MediaManager.sln
- MediaManager/Plugin.MediaManager.Abstractions/MediaQueue.cs
- Plugin.MediaManager.Abstraction/MediaFile.cs
- Plugin.MediaManager.Abstraction/Plugin.MediaManager.Abstraction.csproj
- Plugin.MediaManager.Abstraction/Tests/MediaQueueTests.cs
- Plugin.MediaManager.Abstraction/packages.config
I did quite some changes to the MediaQueue, packed with this implemenation.
I've just added a property-changed event when `Count` or `Current`, forwarded the internal queue changes (before the `CollectionChanged` event never got triggered), fixed the randomness of the shuffle-method (according to http://stackoverflow.com/questions/767999/random-number-generator-only-generating-one-random-number#answer-768001) and started off with unit-tests - mainly for the MediaQueue implementation.
> MediaQueue: Added tiggers and started off with unit-tests

- MediaManager/Plugin.MediaManager.Android/MediaPlayerService/MediaPlayerService.cs
- MediaManager/Plugin.MediaManager.Android/MediaSession/MediaSessionManager.cs
Updated MediaPlayerService.OnError and MediaSessionManager.UpdatePlaybackState so that if it's updating the state to StateError, it can pass an error message, which the documentation for PlaybackStateCompat.Builder says should be set.
> Android: Updated MediaPlayerService.OnError and MediaSessionManager.UpdatePlaybackState

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaManagerBase.cs
- MediaManager/Plugin.MediaManager.Android/Environment.txt
- MediaManager/Plugin.MediaManager.Android/MediaPlayerService/MediaPlayerService.cs
- MediaManager/Plugin.MediaManager.Android/Plugin.MediaManager.Android.csproj
1) Removed exception thrown by MediaManagerBase.CurrentPlaybackManager getter, and allowed it to return null instead. Added null reference checks to code that accessed getter. #76 
2) Modified MediaPlayerService.Play() so that if there is an IllegalStateException thrown by _mediaPlayer.PrepareAsync(), it retries several times.
3) Modified MediaPlayerService.SetMediaPlayerDataSource() to avoid some exceptions.
4) Fixed #87
> A couple Android fixes

- .gitignore
- MediaManager/Plugin.MediaManager.Abstractions/Plugin.MediaManager.Abstractions.csproj
- MediaManager/Plugin.MediaManager.Android/Plugin.MediaManager.Android.csproj
- MediaManager/Plugin.MediaManager.ExoPlayer/Plugin.MediaManager.ExoPlayer.csproj
- MediaManager/Plugin.MediaManager.MacOS/Plugin.MediaManager.MacOS.csproj
- MediaManager/Plugin.MediaManager.Reactive/Plugin.MediaManager.Reactive.csproj
- MediaManager/Plugin.MediaManager.iOS/Plugin.MediaManager.iOS.csproj
- MediaManager/Plugin.MediaManager.tvOS/Plugin.MediaManager.tvOS.csproj
- MediaManager/Plugin.MediaManager/Plugin.MediaManager.csproj
This pull requests makes it so all warnings about missing comments on publicly accessible variables no longer generate warnings.
I also added project.lock.json to gitignore because the it crashed SourceTree all the time and it is generally recommended to not include it in source control
> Ignore XML comments missing warning

- MediaManager/Plugin.MediaManager.Abstractions/IMediaQueue.cs
- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaQueue.cs
- MediaManager/Plugin.MediaManager.Tests/Tests/MediaQueueTests.cs
This is a breaking change, if this is taken in it will require people to fix all references from Shuffle to IsShuffled.
> IMediaQueue Shuffle rename to IsShuffled

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaQueue.cs
I moved the raising of this event handler so when the listener gets the event, the Current property has it's right value, which wasn't the case before when you did an unshuffle because the Index was set after the queue was replaced (And the CollectionChanged event raised).
> Moved CollectionChanged raising to end of IsShuffling setter.

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/PlaybackController.cs
Changed the order to go from RepeatNone --> RepeatAll --> RepeatOne. Which is more intuitive IMO since you're going from least repeating to most. This is also the way Spotify and most other players have it.
> Change order of Repeat toggle to be more intuitive

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
The behaviour for buffering changed in iOS 10. See the following property that was introduced:
https://developer.apple.com/reference/avfoundation/avplayer/1643482-automaticallywaitstominimizestal
> Fixed issue with buffering on iOS 10 and greater.

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
It's now using a new instance of AVPlayer each time. The reason is that previously when a media failed, the AVPlayer did not play any other AVPlayerItems.
Also fixed an issue where the `AVPlayer.Status` and `AVPlayer.Error` property instead of the `AVPlayerItem.Status` and `AVPlayerItem.Error` property, which also caused some issues.
> Various fixes and refactorings for iOS

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaManagerBase.cs
Since the exceptions are already reported using the MediaFileFailed event, it is unnecessary to rethrow the exception. If this is not explicitly catched by the invoking method, the app will crash. I therefore remove the throw expression to avoid crashes that occurred.
> Fixed issue that causes a crash when a media file fails.

- MediaManager/Plugin.MediaManager.ExoPlayer/ExoPlayerAudioService.cs
Because this override method was missing, the stop was not implemented in the ExoPlayer.
> Added stop method to ExoPlayer.

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
This should fix the following stack-trace I got reported at Insights on an iOS device:
> System.ArgumentExceptionTimeSpan does not accept floating point Not-a-Number values.
>
> System.TimeSpan.Interval(double value, int scale)
> System.TimeSpan.FromSeconds(double value)
> Plugin.MediaManager.AudioPlayerImplementation.ObserveLoadedTimeRanges()
> Plugin.MediaManager.AudioPlayerImplementation.ObserveValue(NSString keyPath, NSObject ofObject, NSDictionary change, IntPtr context)
> UIKit.UIApplication.UIApplicationMain(int, string[], intptr, intptr)(wrapper managed-to-native)
> UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)
Since this error was thrown in production, I have no line-numbers attached to it.
> Fixed an argument exception (TimeSpan.FromSeconds was called with NaN)

- MediaManager/Plugin.MediaManager.Abstractions/Implementations/MediaManagerBase.cs
Should fix this stacktrace:
> System.NullReferenceExceptionObject reference not set to an instance of an object
> 
> Plugin.MediaManager.Abstractions.Implementations.MediaManagerBase.get_Duration()<37290f3ebc7342948d1e410443a3c068>:0
> Plugin.MediaManager.Abstractions.Implementations.PlaybackController.<SeekTo>d__20.MoveNext()<37290f3ebc7342948d1e410443a3c068>:0
> Plugin.MediaManager.Abstractions.Implementations.PlaybackController.<SeekToStart>d__17.MoveNext()<37290f3ebc7342948d1e410443a3c068>:0
> Plugin.MediaManager.Abstractions.Implementations.PlaybackController.<PlayPrevious>d__16.MoveNext()<37290f3ebc7342948d1e410443a3c068>:0
> Fixed calling `Position`, `Duration` or `Buffered` when `CurrentPlaybackManager` isn’t defined

- MediaManager/Plugin.MediaManager.Android/Audio/AudioPlayerBase.cs
- MediaManager/Plugin.MediaManager.Android/Video/VideoPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.UWP/AudioPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.UWP/VideoPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
- MediaManager/Plugin.MediaManager.iOS/VideoPlayerImplementation.cs
This should catch up with devision-by-zero handling, when the duration is 0, the position gets `Infinite` or `-Infinite` (and not `NaN` as claimed in the UWP version - see the example here: https://msdn.microsoft.com/en-us/library/system.double.isinfinity(v=vs.110).aspx).
I've also fixed #147 for videos 😉
> Updated division-by-zero handling

- MediaManager/Plugin.MediaManager.iOS/AudioPlayerImplementation.cs
> Fixed issue with rate observer not being properly unregistered.

- MediaManager.iOS/MediaNotificationManagerImplementation.cs
Should fix the following crash I found in Insights:
```
0 libsystem_kernel.dylib __pthread_kill (in libsystem_kernel.dylib) + 8
1 libsystem_c.dylib abort (in libsystem_c.dylib) + 140
2 MyMediaPlayerApp -[PLCrashReporter generateLiveReportWithThread:] (in 3ec122779f9f33fb9cd4636415e6dba8) + 0
3 CoreFoundation __handleUncaughtException (in CoreFoundation) + 644
4 libobjc.A.dylib objc_terminate() (in libobjc.dylib) + 112
5 libc++abi.dylib std::__terminate() (in libc++abi.dylib) + 16
6 libc++abi.dylib _cxxabiv1::exception_cleanup_func() (in libc++abi.dylib) + 0
7 libobjc.A.dylib objc_exception_destructor() (in libobjc.dylib) + 0
8 CoreFoundation -[NSException initWithCoder:] (in CoreFoundation) + 0
9 MediaPlayer -[MPMediaItemArtwork initWithImage:] (in MediaPlayer) + 216
10 MyMediaPlayerApp …
```
> Updated call for MPMediaItemArtwork to confirm cover isn’t nil

- MediaManager.Android/Video/VideoPlayerImplementation.cs
on iOs platform there's no multiplication by 100 as removed from android, what force users to use workaround to treat this.
> Normalize progress on Android and iOS

- .gitignore
I found that Git is recently finding the following changes when building the solution:
> modified:   ../MediaManager.Forms/MediaManager.Forms.UWP/Plugin.MediaManager.Forms.UWP.nuget.targets
> modified:   ../Samples/Forms/MediaForms.UWP/MediaForms.UWP.nuget.targets
I'm not sure if it's because I upgraded to VS 2017, or some other reason. These appear to be user-specific files, so I added these types of files to .gitignore.
> Updated .gitignore to include *.nuget.targets" files.

- MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
Removed logic from MediaServiceBase.CheckIfFileAlreadyIsPlaying() that prevented playing the same media file twice in a row. This fixes Issue #71 
I'm not sure of the original purpose for that piece of logic. I have been testing it and have found no ill effects of removing it.  If you know any needed purpose for it, let me know and maybe we can figure out a solution that works all around.
> Fixed Issue #71

- MediaManager.Android/MediaSession/MediaSessionManager.cs
Fixed issue where if you set a custom MediaNotificationManager, it would get overridden when the next media played.
> Fixed Issue #192

- MediaManager.UWP.Tests/Plugin.MediaManager.UWP.Tests.csproj
- MediaManager.UWP.Tests/Unit/MediaButtonPlaybackControllerTest.cs
- MediaManager.UWP.Tests/Unit/PlaybackControllerProviderMock.cs
- MediaManager.UWP/IPlaybackControllerProvider.cs
- MediaManager.UWP/MediaButtonPlaybackController.cs
- MediaManager.UWP/MediaManagerImplementation.cs
- MediaManager.UWP/Plugin.MediaManager.UWP.csproj
- MediaManager.UWP/Properties/AssemblyInfo.cs
- MediaManager.UWP/SystemWrappers/ISystemMediaTransportControlsButtonPressedEventArgsWrapper.cs
- MediaManager.UWP/SystemWrappers/ISystemMediaTransportControlsWrapper.cs
- MediaManager.UWP/SystemWrappers/SystemMediaTransportControlsButtonPressedEventArgsWrapper.cs
- MediaManager.UWP/SystemWrappers/SystemMediaTransportControlsWrapper.cs
This is a step towards solving issue #229. The PlaybackController instance now reflects the setting of the PlaybackController property on MediaManagerInstance for UWP. This would also need to be done for Android (and I guess IOS)
> PlaybackController instance is no longer lost

- MediaManager.Abstractions/Implementations/MediaFile.cs
- MediaManager.iOS/MediaExtractorImplementation.cs
- Samples/Forms/MediaForms/HomePage.xaml
- Samples/Forms/MediaForms/HomePage.xaml.cs
Changes to support user entered metadata for IOS Remote Control.
Plus additions to the MediaForms Sample project to show how these changes work, plus a stop button.
And the Implementations MediaFile update to include ExtractMetadata.  I forgot this one in the android PR.
> Changes to resolve metadata issues on IOS

- MediaManager.Abstractions/IMediaManager.cs
- MediaManager.Abstractions/Implementations/MediaManagerBase.cs
- MediaManager.Abstractions/Implementations/MediaQueue.cs
- MediaManager.Abstractions/Implementations/PlaybackController.cs
- MediaManager.Android/Audio/AudioPlayerImplementation.cs
- MediaManager.Android/Audio/AudioPlayerService.cs
- MediaManager.Android/Audio/MediaSessionCallback.cs
- MediaManager.Android/MediaItemExtensions.cs
- MediaManager.Android/NotificationManagerImplementation.cs
- MediaManager.Android/Video/VideoPlayerImplementation.cs
- MediaManager.Android/VolumeManagerImplementation.cs
- MediaManager/CrossMediaManager.cs
- Samples/Forms/Droid/Properties/AndroidManifest.xml
Changed MediaManagerBase back to match initial "Play" call after NetStandard Branch and mediaBrowser.Connect() no longer crashes.  The problem is somewhere in the "PlayCurrent" functionality.
Here are the key lines of code in MediaManagerBase (209-213) that resolved the SIGSEVG:
//await RaiseMediaItemFailedEventOnException(async () =>
//{
//    await PlayCurrent();
//});
await AudioPlayer.Play(MediaItem);
> NETSTANDARD: Found SIGSEVG Crash

- Samples/Simple/MediaSample.Droid/MainActivity.cs
Fixes minor compilation error and sets UseExoPlayer = false by default.
> Fixes for Sample (Simple/MediaSample.Droid) app does not work #299

- MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
- MediaManager.ExoPlayer/ExoPlayerAudioService.cs
- MediaManager.iOS/AudioPlayerImplementation.cs
I removed the preceeding OnStatusChanged calls as OnStatusChanged is invoked within the UpdatePlaylistState function.
> Duplicate StatusChanged event calls (Resolves Issue #303)

- MediaManager.Android/MediaSession/MediaSessionManager.cs
Right now, `MediaNotificationManagerImplementation.AddActionButtons` is not working, since MediaQueue is always `null`. This is, because `UpdateAndroidNotificationManagerSettings` is called before _notificationManager is constructed in `InitMediaSession`. So buttons would otherwise only work, if the `NotificationManager` property was set.
> Fix UpdateAndroidNotificationManagerSettings call

- MediaManager.iOS/MediaNotificationManagerImplementation.cs
Adding a URI to the MediaFile Metadata AlbumArtUri property will now display the artwork in the IOS lock screen
> Fix to allow loading IOS Artwork from URL via AlbumArtUri

- MediaManager.Android/Video/VideoPlayerImplementation.cs
Changes the VideoPlayerImplementation Duration and Position to TimeSpan.FromMilliseconds because the Android VideoViewCanvas.CurrentPosition provides milliseconds, not seconds.
> Fixed Position and Duration Problem for Android Devices

- MediaManager.Android/MediaSession/MediaSessionManager.cs
Minor bug fix while trying to figure out the class.
As title says, use the Metadata.Album for Album, instead of Artist.
> Use MetaData.Album for Album, rather than MetaData.Artist

- MediaManager.ExoPlayer/ExoPlayerAudioService.cs
When calling Stop() it currently changes state to "Stopped", "Loading" then "Playing". This is not what you expect to happen. According to the [docs of the ExoPlayer](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.html#STATE_IDLE) the STATE_IDLE is when it has nothing to play, so converting it to the MediaPlayerStatus.Stopped seem most suitable.
Furthermore i noticed that the `GetCompatValueByStatus(MediaPlayerStatus state)` returns `PlaybackStateCompat.StateSkippingToQueueItem;` if `MediaPlayerStatus.Loading` I believe that is wrong? I haven't changed it as i thought it might have impact on queued items?
**Commits**:
StateIdle == Nothing to play according to exoplayer docs. Its also the default state, and Stopped is the default state of …
> Exoplayer needs to call Stop() twice before state is actually "Stopped".

- MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
- MediaManager.ExoPlayer/ExoPlayerAudioService.cs
MediaFileFailed was wrongly used to tell if there was an error with the playback. The MediaFileFailed says its used for Media metadata fails, so i've changed it to use the MediaFailed event instead just as the other players on the other platforms.
> MediaFailed is never called, as it was set up wrong  on android.

- MediaManager.Android/MediaPlayerService/MediaServiceBase.cs
Request AudioFocus.Gain instead of LossTransientCanDuck.
If its really needed for anyone to play with LossTransientCanDuck we should make it possible to change this during playback start.
> Use AudioFocus.Gain

- MediaManager/IMediaPlayer.cs
- MediaManager/MediaManagerBase.cs
- MediaManager/Platforms/Android/Media/MediaPlayer.cs
- MediaManager/Platforms/Android/MediaManagerImplementation.cs
- MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
- MediaManager/Platforms/Apple/Media/AppleMediaPlayer.cs
- MediaManager/Platforms/Apple/Media/QueueDataAdapter.cs
- MediaManager/Platforms/Tizen/Media/MediaPlayer.cs
- MediaManager/Platforms/Tizen/MediaManagerImplementation.cs
- MediaManager/Platforms/Wpf/MediaManagerImplementation.cs
- MediaManager/Playback/IPlaybackManager.cs
- MediaManager/Playback/RepeatMode.cs
- Samples/ElementPlayer.Core/ViewModels/PlayerViewModel.cs
Feature
We do not use the queue in iOS and the repeat does not work for either iOS or android
We do use the queue implementation (and can handle multiple files at once to accomodate so) and we can repeat playing movies
No
> iOS queue implementation and repeat implementation

- MediaManager/Media/MediaItemExtensions.cs
Bug fix
Uses `Title` property instead of `DisplayTitle` when `DisplayTitle` has a value.
Uses `DisplayTitle` property when `DisplayTitle` has a value.
It fixes the precedence to use the `DisplayTitle` property when it exists instead of the `Title` property.
Specify a `DisplayTitle` that is different than `Title` and see it display now!
- [X ] All projects build
- [ X] Follows style guide lines 
- [ X] Rebased onto current develop
> Fix to use DisplayTitle when specified.

- MediaManager/Platforms/Uap/Media/MediaItemExtensions.cs
- MediaManager/Platforms/Uap/Player/WindowsMediaPlayer.cs
- [-] All projects build
- I couldn't get the whole project to build before.  See https://github.com/martijn00/XamarinMediaManager/pull/531
- [-] Follows style guide lines
- Need a link to this.
> Allow UWP to play local files given a dos path to media

- MediaManager/Platforms/Uap/Player/WindowsMediaPlayer.cs
* Try playing a playlist from the first item
* Try playing a playlist from the seconds item
* https://github.com/martijn00/XamarinMediaManager/issues/533
> Pass whole playlist to UWP and start playing from the selected item

- MediaManager/Platforms/Ios/Video/PlayerViewController.cs
- MediaManager/Platforms/Ios/Video/VideoView.cs
bug fix
Video hung-up on the 2nd play
The player is detached on leaving the player view to continue playing in the background and restart video correctly.
no
#534
> Detach player for play audio in background and fix 2nd play on iOS

- Samples/ElementPlayer.Core/ViewModels/HomeViewModel.cs
- Samples/ElementPlayer.Core/ViewModels/MiniPlayerViewModel.cs
- Samples/ElementPlayer.Core/ViewModels/PlayerViewModel.cs
- Samples/ElementPlayer.iOS/Views/PlayerViewController.cs
fix
Play is called twice in example project on native ios in PlayerViewController
Play is called only from Manager in the example project
no
> Remove MediaItemToPlay parameter from ViewModel

- MediaManager.Forms/VideoView.cs
fix
VideoView is not working correctly when the source is a string in Xamarin.Forms
VideoView is working correctly when the source is a string in Xamarin.Forms
no
> Fix for string source in VideoView in Xamarin.Forms

- MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
- MediaManager/Platforms/Apple/Player/AppleMediaPlayer.cs
Bug fix
MediaItemChanged is not fired on PlayNext on iOS
MediaItemChanged is fired on successful PlayNext on iOS
no
#544
> MediaItemChanged is fired directly on PlayNext in AppleMediaManager

- MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs
The `Milliseconds` property of a `TimeSpan` is just the milliseconds component (i.e., the fractional part of the second component).
This change uses the `TotalMilliseconds` property, which is the **total** milliseconds in a `TimeSpan` (and casts the value to a `long`, since it is a `double`).
> Seek based on TotalMilliseconds, not ms component.

- MediaManager/MediaManagerBase.cs
fix
MediaItemChanged is firing multiple times for every media item
MediaItemChanged is firing only once for every media item
no
#501
> Prevent to fire MediaItemChanged more than once

- MediaManager/Platforms/Apple/Player/AppleMediaPlayer.cs
This is an enhancement on the SeekTo method for iOS, which didn't have enough precision and would seek to the desired time with a difference of ~500ms.
The precision of the SeekTo method was small, and the position is of by ~500ms.
This change uses the current media item's timescale to navigate correctly to the desired position.
Use the SeekTo method by passing milliseconds on the timespan on iOS, and check that the position is the desired or at least the error difference is really small.
> [iOS] - Improved Precision on SeekTo for iOS

- appveyor.yml
- build.cake
I was not able to build the plugin with only vs2019 installed (no vs2017 also)
* Search for MSBuild in "Current" if not found in "15.0" folder
* Also: Update Cake.Git to v0.21.0
* My environment didn't like v0.17.0 - maybe this is not universal
I still didn't get everything to build in vs2019, but the Cake build succeeded enough to build the plugin
> vs2019 build fixes

- README.md
Xamarin.com blog has been fully migrated to devblogs.microsoft.com and there's no redirect from the old articles to the new system. I updated the link to point to the correct location.
Docs update
Xamarin Blog link redirects to the main Xamarin blog on devblogs.microsoft.com
Xamarin Blog link goes directly to the correct article
No
Click the link :)
> Updated the Xamarin Blog link

- MediaManager/Queue/MediaQueue.cs
- MediaManager/Queue/QueueEndedEventArgs.cs
Bug fix
QueueEnded event is fired before the last MediaItem
QueueEnded is fired after last MediaItem finishes
> Fix QueueEnded event invoke

- MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs
fix
lastWindowIndex is not reset.
lastWindowIndex is reset when we are playing the new MediaItems.
> Reset lastWindowIndex on idle state

- MediaManager/MediaManagerBase.cs
- MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
fix
Current index is not reset on ClearQueueInPlay on iOS
CurrentIndex is reset correctly
> Fix clear queue on iOS

- MediaManager/Queue/MediaQueue.cs
> Nullcheck on Current when Current Index changed

- MediaManager/Platforms/Apple/Player/AppleMediaPlayer.cs
Changes:
- If the source is a stream, the metadata changes. So it have to be overwritten
- The Artist have to be set because the `DisplayTitle` is the audio stream file name like "MyStation.m3u"
Bug fix
The `Artist` and `Title` not set. If you want to use `DisplayTitle` its not set correctly.
Artist and Title set correctly if the source is a stream (audio or video).
No
Try a webradio
#633
> Fixed TimedMetaDataChanged

- MediaManager.FFmpegMediaMetadataRetriever/FFmpegMetadataProvider.cs
- MediaManager/Platforms/Android/Media/ID3Provider.cs
- MediaManager/Platforms/Apple/Media/AVAssetProvider.cs
Android - It takes Microsecond, so multiplying milliseconds with 1000
iOS, CMTime ticks in 1000's
Bug Fix
GetFrame always takes initial frame since rounding logic is wrong
Bug Fixes Only
No
> Fixed Logic for GetFrame

- MediaManager/Platforms/Apple/Notifications/NotificationManager.cs
Bug fix
When you are on the notification screen, the seek interval is 10 seconds no matter what you set the seek step too.
If you set the seek interval to say 30, the forward and rewind seek will say 30 instead of 10
No
You must test on a real device, just start playing a track and go to the notification screen. Verify the seek step is consistent with what you set in code.
https://developer.apple.com/documentation/mediaplayer/mpskipintervalcommand/1622899-preferredintervals
- [X ] All projects build
- [N/A] Relevant documentation was updated
> Fix seek interval on iOS

- MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
Bug fix
Audio player randomly crashes on iOS when it returns a NaN time for position
Player doesn't crash
No
Switching between tracks quickly can produce this bug,I think it's more common on the simulator.
- [N/A] Relevant documentation was updated
> Fix random crash on iOS

- MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs
Sometimes when `OnLoadingChanged` was called, `Player.BufferedPosition` would be an invalid value (very large negative number, possibly `long.MinValue`, I didn't check), which is not a valid parameter for `TimeSpan.FromMilliseconds`, and would thus cause a crash.
> Fixed occational crash on Android

- MediaManager/Platforms/Ios/Media/MPMediaItemExtensions.cs
Feature
Does not convert MPMediaItems to MediaItems
Extension methods added to convert MPMediaItems to MediaItems the player understands.
No
Perform a MPMediaQuery and try to play the audio.
```
var musicQuery = MPMediaQuery.SongsQuery;
musicQuery.GroupingType = MPMediaGrouping.Title;
var songs = musicQuery.Items.ToMediaItems();
```
I'm not sure if this is really the correct place to add this. But I figured it would be better to just get something in so that we can discuss if changes are necessary.
#746
> Add extension to handle MPMediaItem

- MediaManager/MediaManagerBase.cs
- MediaManager/Platforms/Apple/Notifications/NotificationManager.cs
This pull request fixes playback position in the iOS control center, which previously did not update in response to the skip forward and backward commands. As part of this change, I've also enabled the direct control of playback position in the iOS notification.
Currently, this library does not update the notification when the user presses the seek buttons in the iOS notification (found in Control Center) for currently playing audio.
The position indicator in the notification updates in response to pressing the seek buttons, and allows direct manipulation of the current playback position with the slider.
Nope.
This only impacts iOS, and can be verified by playing any media.
> improved handling for playback position changes in iOS control center

- MediaManager/IMediaManager.cs
- MediaManager/MediaManagerBase.cs
- README.md
This PR fixes a bug that comes up, when disposing the mediamanager. 
The current behavior is as follows: If I call dispose on the mediaManager, the timer will be stopped and never subscribed to again. For example, I open a video, close the page, call `CrossMediaManager.Current.Dispose()` . Open another video, with calling `CrossMediaManager.Current.Init()`. Now on opening the second video no events are fired from the timer.
The timer starts firing events again after `CrossMediaManager.Current.Init()` was called.
Should not break anything.
Opening multiple videos on different pages, calling dispose every time a page is closed.
> Bugfix Starts the timer again on calling Init()

- MediaManager/Platforms/Android/Playback/PlaybackStateExtensions.cs
Feature
When the player stops because of a network error, MediaManager returns the state Stopped.
When the player stops due to a network error or another error, return the state failed.
If a user of the library wants to handle retries on his own, is important to understand if the player stopped because there was a failure or not. 
No
> When media player state is StateError, return Failed state instead of Stopped.

- MediaManager.Forms/VideoView.cs
- MediaManager/MediaManagerBase.cs
- MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs
- MediaManager/Platforms/Ios/Player/IosMediaPlayer.cs
- MediaManager/Platforms/Mac/Player/MacMediaPlayer.cs
- MediaManager/Platforms/Tizen/Player/TizenMediaPlayer.cs
- MediaManager/Platforms/Uap/Player/WindowsMediaPlayer.cs
- MediaManager/Platforms/Wpf/Player/WpfMediaPlayer.cs
- MediaManager/Playback/IPlaybackManager.cs
- MediaManager/Player/IMediaPlayer.cs
- MediaManager/Player/MediaPlayerBase.cs
- Samples/ElementPlayer.Forms.UI/Pages/PlayerPage.xaml
I have added the IsFullWindow property so that the VideoView control can pass a video to full screen when the native video controls are hidden.
There is no way to put a video in full screen if you have the native video controls hidden.
Now the VideoView control has an IsFullWindow property to add the video to full screen. (only for UWP)
No.
No.
No.
- [Yes ] All projects build
- [Yes ] Follows style guide lines 
- [Yes] Rebased onto current develop
> A IsFullWindow new property has been added and implemented for UWP

- MediaManager/Platforms/Apple/Player/AppleMediaPlayer.cs
Bug fix #841 
Creating a new NSError
Throw an ApplicationException
Jup, an ApplicationException is passed as an argument.
> Avoid creating an NSError

- MediaManager/Platforms/Android/MediaManagerImplementation.cs
This is a bug fix for make the plugin compatible with Android 12. It requires now FLAG_IMMUTABLE (or MUTABLE) for every PendingIntent.GetActivity(), otherwise, it fails to load the app.
The app crashes as soon as it starts, with the error
"Caused by: java.lang.IllegalArgumentException: fr.magina.radioperfecto: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles."
No more crash !
No, it's backward compatible
#845
> Add flag immutable for intent

- MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs
Potential fix for https://github.com/Baseflow/XamarinMediaManager/issues/877 also sets up PlayerNotificationManager in the way Google intends it (Not deprecated)
Notification doesn't spawn correctly.
Notification should spawn correctly.
Haven't been able to test yet.
> Fix: Set PlayerNotificationManager up correctly

- MediaManager/Platforms/Ios/Player/AppleMediaPlayer.cs
[fixes issue #888](https://github.com/Baseflow/XamarinMediaManager/issues/888)
> fixes issue #888, removing already removed observer causes app termination due to NSInvalidArgumentException
